# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  branches:
   develop:
        - step:
            script:
              - apt-get update
              - apt-get install -y zip
              - zip -r application.zip .
              - pipe: atlassian/aws-code-deploy:0.2.10
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_EBS
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  APPLICATION_NAME: $APPLICATION_NAME_CODEDEPLOY
                  S3_BUCKET: $S3_BUCKET
                  COMMAND: 'upload'
                  ZIP_FILE: 'application.zip'
              - pipe: atlassian/aws-code-deploy:0.2.10
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_EBS
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  APPLICATION_NAME: $APPLICATION_NAME_CODEDEPLOY
                  DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP_NAME
                  S3_BUCKET: $S3_BUCKET
                  WAIT: 'true'
                  COMMAND: 'deploy'
                  IGNORE_APPLICATION_STOP_FAILURES: 'true'
                  FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
   master:
        - step:
            script:
              - apt-get update
              - apt-get install -y zip
              - zip -r application.zip .
              - pipe: atlassian/aws-code-deploy:0.2.10
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_EBS
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  APPLICATION_NAME: $APPLICATION_NAME_CODEDEPLOY
                  S3_BUCKET: $S3_BUCKET
                  COMMAND: 'upload'
                  ZIP_FILE: 'application.zip'
              - pipe: atlassian/aws-code-deploy:0.2.10
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_EBS
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  APPLICATION_NAME: $APPLICATION_NAME_CODEDEPLOY
                  DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP_NAME_PROD
                  S3_BUCKET: $S3_BUCKET
                  WAIT: 'true'
                  COMMAND: 'deploy'
                  IGNORE_APPLICATION_STOP_FAILURES: 'true'
                  FILE_EXISTS_BEHAVIOR: 'OVERWRITE'